
/* ===== v4310_finance_investments.js ===== */
/* RUTIN V43.10 — FINANCE + INVESTMENTS UNIFIED */
(function(){
const esc=s=>window.esc?window.esc(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const fmt=v=>money(num(v));
window.financeTabV4310=window.financeTabV4310||'cards';
function ensure(){
 state.cards=Array.isArray(state.cards)?state.cards:[]; state.flexAccounts=Array.isArray(state.flexAccounts)?state.flexAccounts:[]; state.investments=Array.isArray(state.investments)?state.investments:[];
 state.investments=state.investments.map(x=>{if(x&&x.v4310)return x; const qty=num(x.quantity||x.qty)||1, unit=(x.unitPrice!=null?num(x.unitPrice):num(x.amount)); return {...x,v4310:true,type:x.type||'DİĞER',name:x.name||x.title||'YATIRIM',quantity:qty,unitPrice:unit,commission:num(x.commission),extraCost:num(x.extraCost),date:x.date||iso()};});
}
function investmentCost(x){return num(x.quantity)*num(x.unitPrice)+num(x.commission)+num(x.extraCost)}
window.setFinanceTabV4310=function(t){financeTabV4310=t;screen='finance';render()};
window.openInvestmentsV4310=function(){financeTabV4310='investments';screen='finance';render()};
finance=function(){ensure(); const tab=financeTabV4310;
 const cards=state.cards.map(c=>`<button class="fin4310Card credit" onclick="openCardMenuV4310('${c.id}')"><span class="fin4310Badge">KREDİ KARTI</span><b>${esc(c.name||'KREDİ KARTI')}</b><strong>${fmt(c.balance)}</strong><div><span>LİMİT <b>${fmt(c.limit)}</b></span><span>KULLANILABİLİR <b>${fmt(Math.max(0,num(c.limit)-num(c.balance)))}</b></span></div><small>Dokun · işlemler</small></button>`).join('');
 const flex=state.flexAccounts.map(a=>`<button class="fin4310Card flex" onclick="openFlexMenuV4310('${a.id}')"><span class="fin4310Badge">ESNEK HESAP</span><b>${esc(a.name||'ESNEK HESAP')}</b><strong>${fmt(a.balance)}</strong><div><span>LİMİT <b>${fmt(a.limit)}</b></span><span>KULLANILABİLİR <b>${fmt(Math.max(0,num(a.limit)-num(a.balance)))}</b></span></div><small>Dokun · işlemler</small></button>`).join('');
 const inv=state.investments.map(x=>`<button class="inv4310Row" onclick="openModal('editInvestment4310:${x.id}')"><span class="inv4310Icon">◆</span><span><small>${esc(x.type||'DİĞER')} · ${esc(x.date||'')}</small><b>${esc(x.name||'YATIRIM')}</b><em>${num(x.quantity).toLocaleString('tr-TR')} × ${fmt(x.unitPrice)}</em></span><strong>${fmt(investmentCost(x))}</strong></button>`).join('');
 const invTotal=state.investments.reduce((a,x)=>a+investmentCost(x),0);
 return `${header('FİNANS',true)}<div class="finance4310"><div class="financeTabs4310"><button class="${tab==='cards'?'active':''}" onclick="setFinanceTabV4310('cards')">▰<span>KARTLAR</span></button><button class="${tab==='accounts'?'active':''}" onclick="setFinanceTabV4310('accounts')">◇<span>HESAPLAR</span></button><button class="${tab==='investments'?'active':''}" onclick="setFinanceTabV4310('investments')">◆<span>YATIRIMLAR</span></button></div>
 ${tab==='cards'?`<div class="fin4310Head"><div><small>FİNANS</small><b>KREDİ KARTLARI</b></div><button onclick="openModal('addCard')">＋ KART</button></div><div class="fin4310Grid">${cards||'<div class="notice">HENÜZ KREDİ KARTI YOK.</div>'}</div>`:''}
 ${tab==='accounts'?`<div class="fin4310Head"><div><small>FİNANS</small><b>ESNEK HESAPLAR</b></div><button onclick="openModal('addFlex')">＋ HESAP</button></div><div class="fin4310Grid">${flex||'<div class="notice">HENÜZ ESNEK HESAP YOK.</div>'}</div>`:''}
 ${tab==='investments'?`<div class="fin4310Head"><div><small>TOPLAM GERÇEK MALİYET</small><b>${fmt(invTotal)}</b></div><button onclick="openModal('investment4310')">＋ YATIRIM</button></div><div class="inv4310Note">CANLI FİYAT YOK · KÂR/ZARAR YOK · SADECE GERÇEK MALİYET</div><div class="inv4310List">${inv||'<div class="notice">HENÜZ YATIRIM KAYDI YOK.</div>'}</div>`:''}</div>`;
};
investments=function(){openInvestmentsV4310();return finance()};
window.openCardMenuV4310=function(id){const c=state.cards.find(x=>x.id===id);if(!c)return; showDrawer4310('KREDİ KARTI',c.name,fmt(c.balance),`<button onclick="closeDrawer4310();openModal('cardSpend:${id}')">＋ HARCAMA EKLE</button><button onclick="closeDrawer4310();openModal('cardPay4310:${id}')">✓ ÖDEME YAPTIM</button><button onclick="closeDrawer4310();openModal('editCard:${id}')">✎ DÜZENLE</button><button class="danger" onclick="deleteCardV39('${id}')">× SİL</button>`)};
window.openFlexMenuV4310=function(id){const a=state.flexAccounts.find(x=>x.id===id);if(!a)return;showDrawer4310('ESNEK HESAP',a.name,`Kullanılan ${fmt(a.balance)} · Kullanılabilir ${fmt(Math.max(0,num(a.limit)-num(a.balance)))}`,`<button onclick="closeDrawer4310();openModal('flexSpend4310:${id}')">＋ HARCAMA EKLE</button><button onclick="closeDrawer4310();openModal('flexPay4310:${id}')">✓ ÖDEME YAPTIM</button><button onclick="closeDrawer4310();openModal('editFlex:${id}')">✎ DÜZENLE</button><button class="danger" onclick="deleteFlexV4310('${id}')">× SİL</button>`)};
window.showDrawer4310=function(type,name,stat,actions){closeDrawer4310();const el=document.createElement('div');el.className='drawer4310';el.innerHTML=`<div class="drawer4310Grip"></div><div class="drawer4310Head"><div><small>${esc(type)}</small><b>${esc(name||type)}</b></div><button onclick="closeDrawer4310()">×</button></div><strong class="drawer4310Stat">${stat}</strong><div class="drawer4310Actions">${actions}</div>`;document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'))};
window.closeDrawer4310=function(){document.querySelectorAll('.drawer4310').forEach(x=>x.remove())};
window.deleteFlexV4310=function(id){if(!confirm('ESNEK HESAP SİLİNSİN Mİ?'))return;state.flexAccounts=state.flexAccounts.filter(x=>x.id!==id);save();closeDrawer4310();render()};
const oldModal=modalHtml;
modalHtml=function(k){ensure();let title='',body='';
 if(k==='investment4310'||k.startsWith('editInvestment4310:')){const id=k.split(':')[1]||'',x=state.investments.find(z=>z.id===id)||{};title=id?'YATIRIMI DÜZENLE':'YATIRIM EKLE';body=`<form onsubmit="submitInvestment4310(event,'${id}')"><div class="field"><label>YATIRIM TÜRÜ</label><select name="type">${['HİSSE','FON','DÖVİZ','ALTIN','GÜMÜŞ','KRİPTO','DİĞER'].map(v=>`<option ${v===(x.type||'DİĞER')?'selected':''}>${v}</option>`).join('')}</select></div>${field('name','YATIRIM / HİSSE ADI',x.name||'')}${field('quantity','ADET / GRAM / MİKTAR',x.quantity||1,'number')}${field('unitPrice','BİRİM ALIŞ FİYATI',x.unitPrice||0,'number')}${field('commission','KOMİSYON',x.commission||0,'number')}${field('extraCost','EKSTRA MALİYET / GİDER',x.extraCost||0,'number')}${field('date','ALIŞ TARİHİ',x.date||iso(),'date')}<div class="investmentCalc4310">YATIRIM BEDELİ <b id="invBase4310">${fmt(num(x.quantity||1)*num(x.unitPrice))}</b><br>TOPLAM MALİYET <strong id="invTotal4310">${fmt(investmentCost(x))}</strong></div><button class="primary">KAYDET</button>${id?`<button type="button" class="secondary dangerBtn" onclick="deleteInvestment4310('${id}')">YATIRIMI SİL</button>`:''}</form>`;}
 else if(k.startsWith('cardPay4310:')){const id=k.split(':')[1],c=state.cards.find(x=>x.id===id);title='KART ÖDEMESİ';body=`<form onsubmit="submitCardPay4310(event,'${id}')">${field('amount','ÖDENEN TUTAR',c?.balance||0,'number')}${field('date','TARİH',iso(),'date')}<button class="primary">ÖDEMEYİ KAYDET</button></form>`;}
 else if(k.startsWith('flexSpend4310:')){const id=k.split(':')[1];title='ESNEK HESAP HARCAMASI';body=`<form onsubmit="submitFlexSpend4310(event,'${id}')">${field('title','HARCAMA ADI','')}${field('amount','TUTAR',0,'number')}${field('date','TARİH',iso(),'date')}<button class="primary">HARCAMAYI EKLE</button></form>`;}
 else if(k.startsWith('flexPay4310:')){const id=k.split(':')[1],a=state.flexAccounts.find(x=>x.id===id);title='ESNEK HESAP ÖDEMESİ';body=`<form onsubmit="submitFlexPay4310(event,'${id}')">${field('amount','ÖDENEN TUTAR',a?.balance||0,'number')}${field('date','TARİH',iso(),'date')}<button class="primary">ÖDEMEYİ KAYDET</button></form>`;}
 else return oldModal(k);
 return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${title}</b><button class="close" type="button" onclick="event.preventDefault();event.stopPropagation();closeModal();return false">×</button></div>${body}</div></div>`;
};
window.submitInvestment4310=function(e,id=''){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const x={id:id||uid(),v4310:true,type:d.type,name:upper(d.name||'YATIRIM'),quantity:num(d.quantity),unitPrice:num(d.unitPrice),commission:num(d.commission),extraCost:num(d.extraCost),date:d.date||iso()};const i=state.investments.findIndex(z=>z.id===id);if(i>=0)state.investments[i]=x;else state.investments.push(x);save();closeModal();financeTabV4310='investments';render()};
window.deleteInvestment4310=function(id){if(!confirm('YATIRIM SİLİNSİN Mİ?'))return;state.investments=state.investments.filter(x=>x.id!==id);save();closeModal();render()};
window.submitCardPay4310=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),c=state.cards.find(x=>x.id===id);if(!c)return;const a=num(d.amount);c.balance=Math.max(0,num(c.balance)-a);c.transactions=Array.isArray(c.transactions)?c.transactions:[];c.transactions.push({id:uid(),title:'KART ÖDEMESİ',amount:-a,date:d.date||iso(),type:'payment'});save();closeModal();render()};
window.submitFlexSpend4310=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),a=state.flexAccounts.find(x=>x.id===id);if(!a)return;const val=num(d.amount);a.balance=num(a.balance)+val;a.transactions=Array.isArray(a.transactions)?a.transactions:[];a.transactions.push({id:uid(),title:upper(d.title||'HARCAMA'),amount:val,date:d.date||iso(),type:'spend'});save();closeModal();render()};
window.submitFlexPay4310=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),a=state.flexAccounts.find(x=>x.id===id);if(!a)return;const val=num(d.amount);a.balance=Math.max(0,num(a.balance)-val);a.transactions=Array.isArray(a.transactions)?a.transactions:[];a.transactions.push({id:uid(),title:'HESAP ÖDEMESİ',amount:-val,date:d.date||iso(),type:'payment'});save();closeModal();render()};
// Separate investment navigation is redirected to Finance > Investments.
const oldGo=go; go=function(s){if(s==='investments'){financeTabV4310='investments';s='finance'}oldGo(s)};
nav=function(){const items=[['home','⌂','ANA SAYFA','navHome'],['work','✓','İŞ','navWork'],['expenses','₺','HARCAMA','navExpense'],['calendar','31','TAKVİM','navCalendar'],['reports','▥','RAPOR','navReport'],['finance','▰','FİNANS','navInvest'],['more','•••','DAHA FAZLA','navMore']];return `<div class="navV37">${items.map(x=>`<button class="${screen===x[0]?'active ':''}${x[3]}" onclick="go('${x[0]}')"><span class="navIconV37">${x[1]}</span><span class="navLabelV37">${x[2]}</span></button>`).join('')}</div>`};
const priorRender=render;render=function(){if(screen==='investments'){financeTabV4310='investments';screen='finance'}priorRender()};
document.addEventListener('input',e=>{if(e.target.closest&&e.target.closest('form')&&['quantity','unitPrice','commission','extraCost'].includes(e.target.name)){const f=e.target.form,q=num(f.quantity?.value),u=num(f.unitPrice?.value),c=num(f.commission?.value),ex=num(f.extraCost?.value),b=q*u;const be=document.getElementById('invBase4310'),te=document.getElementById('invTotal4310');if(be)be.textContent=fmt(b);if(te)te.textContent=fmt(b+c+ex)}},{passive:true});
ensure();save();
})();

;
