
/* ===== v43_calendar_final.js ===== */
/* RUTIN V43 FINAL CALENDAR INTEGRATION — loaded last to avoid legacy overrides */
(function(){
const V43E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const V43sum=a=>(a||[]).reduce((n,x)=>n+(Number(x.amount)||0),0);
const V43road=x=>x&&(x.sourceType==='workRoad'||x.workId||(String(x.category||'').toUpperCase()==='YOL'&&String(x.note||'').toUpperCase().includes('YOL')));
const V43workIncome=x=>Number(x.amount)||((Number(x.hours)||0)*(Number(x.rate)||0));
function v43MonthPrefix(){const d=new Date(calendarCursor);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function v43Icon(x){const c=String(x?.category||'').toUpperCase();return c==='YOL'?'🚗':c==='MARKET'?'🛒':c==='FIRIN'?'🥖':c==='HARÇLIK'?'₺':c==='YEMEK'?'🍽️':'▤'}
window.v43CalTouchStart=function(e){window.__v43CalX=e.touches?.[0]?.clientX||0};
window.v43CalTouchEnd=function(e){const dx=(e.changedTouches?.[0]?.clientX||0)-(window.__v43CalX||0);if(Math.abs(dx)>55)moveCalendar(dx<0?1:-1)};
window.v43JumpCalendar=function(v){if(!v)return;calendarCursor=new Date(v+'-01T12:00:00');modal=null;screen='calendar';render()};

calendarScreen=function(){
 const d=new Date(calendarCursor),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),offset=(new Date(y,m,1).getDay()+6)%7,prefix=`${y}-${String(m+1).padStart(2,'0')}`;
 let cells='';for(let i=0;i<offset;i++)cells+='<div class="daySpacer premiumDaySpacer"></div>';
 for(let n=1;n<=days;n++){
  const ds=`${prefix}-${String(n).padStart(2,'0')}`,w=state.work.filter(x=>x.date===ds),ex=state.expenses.filter(x=>x.date===ds);
  const flags={daily:w.some(x=>x.type==='daily'),hourly:w.some(x=>x.type==='hourly'),overtime:w.some(x=>x.type==='overtime'),road:ex.some(V43road),expense:ex.some(x=>!V43road(x))};
  const dots=[flags.daily?'daily':'',flags.hourly?'hourly':'',flags.overtime?'overtime':'',flags.road?'road':'',flags.expense?'expense':''].filter(Boolean).map(c=>`<i class="v43dot ${c}"></i>`).join('');
  cells+=`<button class="day premiumDay v43Day${ds===iso()?' today':''}" onclick="openModal('day:${ds}')"><span class="dayNumber">${n}</span><span class="v43Dots">${dots}</span></button>`;
 }
 const mw=state.work.filter(x=>String(x.date||'').startsWith(prefix)),me=state.expenses.filter(x=>String(x.date||'').startsWith(prefix)),mi=state.incomes.filter(x=>String(x.date||'').startsWith(prefix));
 const workedDays=new Set(mw.map(x=>x.date)).size,hours=mw.filter(x=>x.type==='hourly').reduce((n,x)=>n+(Number(x.hours)||0),0),ot=mw.filter(x=>x.type==='overtime').reduce((n,x)=>n+(Number(x.hours)||0),0),income=V43sum(mi)+mw.reduce((n,x)=>n+V43workIncome(x),0),expense=V43sum(me),remain=income-expense,mn=d.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}).toUpperCase();
 return `${header('TAKVİM',true)}<div class="v43CalendarWrap" ontouchstart="v43CalTouchStart(event)" ontouchend="v43CalTouchEnd(event)"><button class="dateJumpMini" onclick="openModal('dateJump')">◉ AY / YIL HIZLI SEÇ</button><div class="calendarTitleRow premiumMonthRow"><button class="calendarArrow" onclick="moveCalendar(-1)">‹</button><div><b>${mn}</b><small>SAĞA / SOLA KAYDIRARAK AY DEĞİŞTİR</small></div><button class="calendarArrow" onclick="moveCalendar(1)">›</button></div><div class="card compactCalendar referenceCalendar premiumCalendarCard"><div class="calendarHead">${['PZT','SAL','ÇAR','PER','CUM','CMT','PAZ'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar premiumCalendarGrid">${cells}</div><div class="calendarLegend premiumLegend v43Legend"><span><i class="v43dot daily"></i>GÜNLÜK</span><span><i class="v43dot hourly"></i>SAATLİK</span><span><i class="v43dot overtime"></i>MESAİ</span><span><i class="v43dot road"></i>YOL</span><span><i class="v43dot expense"></i>HARCAMA</span></div></div></div><div class="v43GoldSummary"><div class="v43GoldTitle">♛ ${mn} · AY ÖZETİ</div>${sumRow('TOPLAM ÇALIŞILAN GÜN',workedDays+' GÜN')}${sumRow('TOPLAM SAATLİK ÇALIŞMA SAATİ',hours+' SAAT')}${sumRow('TOPLAM MESAİ SAATİ',ot+' SAAT')}${sumRow('TOPLAM GELİR',money(income))}${sumRow('TOPLAM HARCAMA',money(expense))}${sumRow('KALAN',money(remain))}</div>`;
};

function v43DayBody(ds){
 const w=state.work.filter(x=>x.date===ds),ex=state.expenses.filter(x=>x.date===ds),roads=ex.filter(V43road),normal=ex.filter(x=>!V43road(x));
 const workRows=w.map(x=>`<div class="detailRecord"><i>${x.type==='daily'?'▣':x.type==='hourly'?'⏱':'✦'}</i><div><b>${V43E(x.title||'ÇALIŞMA')}</b><small>${x.type==='daily'?'GÜNLÜK':x.type==='hourly'?'SAATLİK':'MESAİ'}${x.hours?' · '+x.hours+' SAAT':''} · ${money(V43workIncome(x))}</small></div><div class="v43Actions"><button onclick="openModal('editRecord:work:${x.id}:${ds}')">DÜZENLE</button><button class="dangerBtn" onclick="deleteRecord('work','${x.id}','${ds}')">SİL</button></div></div>`).join('');
 const roadRows=roads.map(x=>`<div class="detailRecord"><i>🚗</i><div><b>YOL GİDERİ</b><small>${V43E(x.method||'NAKİT')}</small></div><strong class="red">-${money(x.amount)}</strong></div>`).join('');
 const expRows=normal.map(x=>`<div class="detailRecord"><i>${v43Icon(x)}</i><div><b>${V43E(x.title||x.category||'HARCAMA')}</b><small>${V43E(x.category||'DİĞER')} · ${V43E(x.method||'NAKİT')}${x.recipient?' · '+V43E(x.recipient):x.person?' · '+V43E(x.person):''}</small></div><strong class="red">-${money(x.amount)}</strong><div class="v43Actions"><button onclick="openModal('editRecord:expense:${x.id}:${ds}')">DÜZENLE</button><button class="dangerBtn" onclick="deleteRecord('expense','${x.id}','${ds}')">SİL</button></div></div>`).join('');
 return `<div class="daySwipeHead"><button onclick="shiftDay('${ds}',-1)">‹</button><div><b>${new Date(ds+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase()}</b><small>SAĞA / SOLA KAYDIRARAK GÜN DEĞİŞTİR</small></div><button onclick="shiftDay('${ds}',1)">›</button></div><div class="section"><b>GÜNLÜK / SAATLİK / MESAİ</b></div>${workRows||'<div class="notice">ÇALIŞMA KAYDI YOK.</div>'}<div class="section"><b>YOL GİDERİ</b></div>${roadRows||'<div class="notice">YOL GİDERİ YOK.</div>'}<div class="section"><b>HARCAMA DETAYLARI</b></div>${expRows||'<div class="notice">HARCAMA YOK.</div>'}`;
}

const v43PrevModal=modalHtml;
modalHtml=function(k){
 if(k.startsWith('day:')){const ds=k.slice(4);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" data-day="${ds}" onclick="event.stopPropagation()"><div class="sheetHead"><b>GÜN DETAYI</b><button class="close" type="button" onclick="closeModal()">×</button></div>${v43DayBody(ds)}</div></div>`}
 if(k==='dateJump'){return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>AY / YIL HIZLI SEÇ</b><button class="close" type="button" onclick="closeModal()">×</button></div><div class="dateJumpBox"><label>AY / YIL</label><input id="v43JumpMonth" type="month" value="${v43MonthPrefix()}"><button class="primary" onclick="v43JumpCalendar(document.getElementById('v43JumpMonth').value)">AYA GİT</button></div></div></div>`}
 return v43PrevModal(k);
};

/* Keep card-linked expense integrity while returning to the selected day. */
submitEditExpense=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),x=state.expenses.find(z=>z.id===id);if(!x)return;const old=Number(x.amount)||0,c=d.category||x.category||'DİĞER';Object.assign(x,{date:d.date,category:c,title:c==='DİĞER'?upper(d.customTitle||x.customTitle||x.title||'DİĞER'):c,customTitle:c==='DİĞER'?upper(d.customTitle||''):'',recipient:d.recipient!==undefined?upper(d.recipient||''):(x.recipient||''),person:d.person!==undefined?d.person:(x.person||''),amount:Number(d.amount)||0,method:d.method||x.method||'NAKİT',note:d.note||''});if(x.sourceType==='card'&&x.cardId&&x.sourceId){const card=state.cards.find(z=>z.id===x.cardId),t=card?.transactions?.find(z=>z.id===x.sourceId);if(card&&t){card.balance=(Number(card.balance)||0)+(x.amount-old);Object.assign(t,{title:x.title,amount:x.amount,date:x.date});}}save();modal='day:'+x.date;render()};
})();

;

/* ===== v43_calendar_v432.js ===== */
/* RUTIN V43.2 — segmented calendar days, drill-down day menu, clickable color-coded month summary */
(function(){
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const road=x=>x&&(x.sourceType==='workRoad'||x.workId||(String(x.category||'').toUpperCase()==='YOL'&&String(x.note||'').toUpperCase().includes('YOL')));
const wIncome=x=>Number(x.amount)||((Number(x.hours)||0)*(Number(x.rate)||0));
const sum=a=>(a||[]).reduce((n,x)=>n+(Number(x.amount)||0),0);
const colors={daily:'#22c55e',hourly:'#3b82f6',overtime:'#d7b45c',road:'#a855f7',expense:'#ff4d5a'};
function prefix(){const d=new Date(calendarCursor);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function segBg(types){if(!types.length)return '';const step=100/types.length;return `linear-gradient(90deg,${types.map((t,i)=>`${colors[t]} ${i*step}% ${(i+1)*step}%`).join(',')})`}
function recType(x,kind){if(kind==='expense')return road(x)?'road':'expense';return x.type||'daily'}
function recLabel(x,kind){if(kind==='expense')return road(x)?'YOL GİDERİ':(x.title||x.category||'HARCAMA');return x.type==='daily'?'GÜNLÜK ÇALIŞMA':x.type==='hourly'?'SAATLİK ÇALIŞMA':'MESAİ'}
function recSub(x,kind){if(kind==='expense')return `${E(x.category||'DİĞER')} · ${E(x.method||'NAKİT')}${x.recipient?' · '+E(x.recipient):x.person?' · '+E(x.person):''} · ${money(x.amount)}`;return `${x.hours?E(x.hours)+' SAAT · ':''}${money(wIncome(x))}`}
function recordButton(x,kind,ds){const t=recType(x,kind);return `<button class="v432Record ${t}" onclick="openModal('calRecord:${kind}:${x.id}:${ds}')"><span class="v432RecordIcon">${t==='daily'?'▣':t==='hourly'?'⏱':t==='overtime'?'✦':t==='road'?(window.rutinCategoryIcon?window.rutinCategoryIcon('YOL'):'🚗'):(window.rutinCategoryIcon?window.rutinCategoryIcon(x.category||'DİĞER'):'▤')}</span><span><b>${E(recLabel(x,kind))}</b><small>${recSub(x,kind)}</small></span><strong>›</strong></button>`}
calendarScreen=function(){
 const d=new Date(calendarCursor),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),offset=(new Date(y,m,1).getDay()+6)%7,p=`${y}-${String(m+1).padStart(2,'0')}`;let cells='';
 for(let i=0;i<offset;i++)cells+='<div class="daySpacer premiumDaySpacer"></div>';
 for(let n=1;n<=days;n++){const ds=`${p}-${String(n).padStart(2,'0')}`,w=state.work.filter(x=>x.date===ds),ex=state.expenses.filter(x=>x.date===ds),types=[];if(w.some(x=>x.type==='daily'))types.push('daily');if(w.some(x=>x.type==='hourly'))types.push('hourly');if(w.some(x=>x.type==='overtime'))types.push('overtime');if(ex.some(road))types.push('road');if(ex.some(x=>!road(x)))types.push('expense');const bg=segBg(types);cells+=`<button class="day premiumDay v432Day${ds===iso()?' today':''}${types.length?' hasData':''}" ${bg?`style="background:${bg}!important"`:''} onclick="openModal('day:${ds}')"><span class="v432DayNo">${n}</span></button>`}
 const mw=state.work.filter(x=>String(x.date||'').startsWith(p)),me=state.expenses.filter(x=>String(x.date||'').startsWith(p)),mi=state.incomes.filter(x=>String(x.date||'').startsWith(p));const dailyDays=new Set(mw.filter(x=>x.type==='daily').map(x=>x.date)).size,hourlyRows=mw.filter(x=>x.type==='hourly'),hourlyDays=new Set(hourlyRows.map(x=>x.date)).size,hour=hourlyRows.reduce((n,x)=>n+(+x.hours||0),0),ot=mw.filter(x=>x.type==='overtime').reduce((n,x)=>n+(+x.hours||0),0),income=sum(mi)+mw.reduce((n,x)=>n+wIncome(x),0),expense=sum(me),mn=d.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}).toUpperCase();
 const S=(type,label,val,cls)=>`<button class="v432Sum ${cls}" onclick="openModal('monthDetail:${type}')"><span>${label}</span><strong>${val}</strong><small>DETAYLAR ›</small></button>`;
 return `${header('TAKVİM',true)}<div class="v43CalendarWrap" ontouchstart="v43CalTouchStart(event)" ontouchend="v43CalTouchEnd(event)"><button class="dateJumpMini" onclick="openModal('dateJump')">◉ AY / YIL HIZLI SEÇ</button><div class="calendarTitleRow premiumMonthRow"><button class="calendarArrow" onclick="moveCalendar(-1)">‹</button><div><b>${mn}</b><small>GÜN KUTUSUNDAKİ HER RENK AYRI BİR KAYDI GÖSTERİR</small></div><button class="calendarArrow" onclick="moveCalendar(1)">›</button></div><div class="card compactCalendar referenceCalendar premiumCalendarCard"><div class="calendarHead">${['PZT','SAL','ÇAR','PER','CUM','CMT','PAZ'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar premiumCalendarGrid">${cells}</div><div class="calendarLegend premiumLegend v43Legend"><span><i class="v43dot daily"></i>GÜNLÜK</span><span><i class="v43dot hourly"></i>SAATLİK</span><span><i class="v43dot overtime"></i>MESAİ</span><span><i class="v43dot road"></i>YOL</span><span><i class="v43dot expense"></i>HARCAMA</span></div></div></div><div class="v432Month"><div class="v432MonthTitle">♛ ${mn} · AY ÖZETİ <small>HER KARTA DOKUN · AYRINTIYI AÇ</small></div><div class="v432SumGrid">${S('worked','TAM GÜN ÇALIŞMA',dailyDays+' GÜN','daily')}${S('hourly','SAATLİK ÇALIŞMA',hourlyDays+' GÜN · '+hour+' SAAT','hourly')}${S('overtime','MESAİ',ot+' SAAT','overtime')}${S('income','TOPLAM GELİR',money(income),'income')}${S('expense','TOPLAM HARCAMA',money(expense),'expense')}${S('remain','KALAN',money(income-expense),'remain')}</div></div>`;
};
function dayMenu(ds){const w=state.work.filter(x=>x.date===ds),ex=state.expenses.filter(x=>x.date===ds);return `<div class="v432DayHead"><button onclick="shiftDay('${ds}',-1)">‹</button><div><b>${new Date(ds+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase()}</b><small>KAYDA DOKUN → DETAY / DÜZENLE / SİL</small></div><button onclick="shiftDay('${ds}',1)">›</button></div><div class="v432DayMenu">${w.map(x=>recordButton(x,'work',ds)).join('')}${ex.map(x=>recordButton(x,'expense',ds)).join('')||(!w.length?'<div class="notice">BU GÜN KAYIT YOK.</div>':'')}</div>`}
function monthDetail(type){const p=prefix(),mw=state.work.filter(x=>String(x.date||'').startsWith(p)),me=state.expenses.filter(x=>String(x.date||'').startsWith(p)),mi=state.incomes.filter(x=>String(x.date||'').startsWith(p));let title='',body='';if(type==='worked'){title='TAM GÜN ÇALIŞMA DETAYI';const dates=[...new Set(mw.filter(x=>x.type==='daily').map(x=>x.date))].sort();body=dates.map(ds=>`<button class="v432DetailLine" onclick="openModal('day:${ds}')"><b>${new Date(ds+'T12:00:00').toLocaleDateString('tr-TR',{day:'numeric',month:'long',weekday:'short'})}</b><span>${mw.filter(x=>x.date===ds).length} kayıt</span><strong>›</strong></button>`).join('')}else if(type==='hourly'||type==='overtime'){title=type==='hourly'?'SAATLİK ÇALIŞMA DETAYI':'MESAİ DETAYI';body=mw.filter(x=>x.type===type).sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<button class="v432DetailLine" onclick="openModal('calRecord:work:${x.id}:${x.date}')"><b>${x.date}</b><span>${x.hours||0} saat · ${money(wIncome(x))}</span><strong>›</strong></button>`).join('')}else if(type==='expense'){title='AYLIK HARCAMA DETAYI';const cats={};me.forEach(x=>{const c=x.category||'DİĞER';cats[c]=(cats[c]||0)+(+x.amount||0)});body=`<div class="v432Breakdown">${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div><b>${E(c)}</b><strong>${money(v)}</strong></div>`).join('')}</div>`+me.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<button class="v432DetailLine" onclick="openModal('calRecord:expense:${x.id}:${x.date}')"><b>${E(x.title||x.category)}</b><span>${x.date} · ${E(x.method||'NAKİT')}</span><strong>${money(x.amount)}</strong></button>`).join('')}else if(type==='income'){title='AYLIK GELİR DETAYI';const workTotal=mw.reduce((n,x)=>n+wIncome(x),0),other=sum(mi);body=`<div class="v432Breakdown"><div><b>ÇALIŞMA GELİRİ</b><strong>${money(workTotal)}</strong></div><div><b>DİĞER GELİRLER</b><strong>${money(other)}</strong></div></div>`+mw.map(x=>`<button class="v432DetailLine" onclick="openModal('calRecord:work:${x.id}:${x.date}')"><b>${E(recLabel(x,'work'))}</b><span>${x.date}</span><strong>${money(wIncome(x))}</strong></button>`).join('')}else if(type==='remain'){title='KALAN DETAYI';const inc=sum(mi)+mw.reduce((n,x)=>n+wIncome(x),0),exp=sum(me);body=`<div class="v432Breakdown"><div><b>TOPLAM GELİR</b><strong>${money(inc)}</strong></div><div><b>TOPLAM HARCAMA</b><strong>${money(exp)}</strong></div><div><b>KALAN</b><strong>${money(inc-exp)}</strong></div></div>`}return {title,body:body||'<div class="notice">BU AY KAYIT YOK.</div>'}}
const prev=modalHtml;modalHtml=function(k){if(k.startsWith('day:')){const ds=k.slice(4);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet v432Sheet" data-day="${ds}" onclick="event.stopPropagation()"><div class="sheetHead"><b>GÜN MENÜSÜ</b><button class="close" onclick="closeModal()">×</button></div>${dayMenu(ds)}</div></div>`}if(k.startsWith('calRecord:')){const [,kind,id,ds]=k.split(':'),arr=kind==='work'?state.work:state.expenses,x=arr.find(z=>String(z.id)===String(id));if(!x)return prev('day:'+ds);const t=recType(x,kind);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet v432Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>KAYIT DETAYI</b><button class="close" onclick="openModal('day:${ds}')">×</button></div><div class="v432RecordHero ${t}"><span>${t==='daily'?'▣':t==='hourly'?'⏱':t==='overtime'?'✦':t==='road'?(window.rutinCategoryIcon?window.rutinCategoryIcon('YOL'):'🚗'):(window.rutinCategoryIcon?window.rutinCategoryIcon(x.category||'DİĞER'):'▤')}</span><b>${E(recLabel(x,kind))}</b><small>${recSub(x,kind)}</small></div><div class="v432RecordActions"><button onclick="openModal('editRecord:${kind}:${x.id}:${ds}')">DÜZENLE</button><button class="dangerBtn" onclick="deleteRecord('${kind}','${x.id}','${ds}')">SİL</button></div></div></div>`}if(k.startsWith('monthDetail:')){const d=monthDetail(k.split(':')[1]);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet v432Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${d.title}</b><button class="close" onclick="closeModal()">×</button></div>${d.body}</div></div>`}return prev(k)};
})();

;
