
/* ===== v436_work_premium.js ===== */
(function(){
 const upper=s=>String(s||'').toLocaleUpperCase('tr-TR');
 const remembered=(k,d)=>state.settings[k]!==undefined?state.settings[k]:d;
 const lastDate=()=>state.settings.lastWorkDate||iso();
 const textarea=(n,l)=>`<div class="field"><label>${l}</label><textarea name="${n}" placeholder="İSTEĞE BAĞLI"></textarea></div>`;
 const payField=(v='unpaid')=>`<div class="field v436Pay"><label>ANA İŞ ÖDEME DURUMU</label><div class="v436PayChoice"><label><input type="radio" name="paymentStatus" value="paid" ${v==='paid'?'checked':''}><span>✓ ÖDEME ALDIM</span></label><label><input type="radio" name="paymentStatus" value="unpaid" ${v!=='paid'?'checked':''}><span>◷ ÖDEME ALMADIM</span></label></div></div>`;
 const roadFields=()=>`<div class="field"><label>YOL PARASI <small>(OPSİYONEL)</small></label><div class="choiceRow"><label><input type="radio" name="road" value="yes" onchange="window.v436RoadToggle&&v436RoadToggle(this.form)">YOL GİDERİ VAR</label><label><input type="radio" name="road" value="no" checked onchange="window.v436RoadToggle&&v436RoadToggle(this.form)">YOK</label></div></div><div class="v436RoadExtra" style="display:none">${field('roadAmount','YOL TUTARI',remembered('lastRoadAmount',0),'number')}<div class="field"><label>YOL ÖDEME ŞEKLİ</label><select name="roadMethod" onchange="window.v436RoadMethod&&v436RoadMethod(this.form)"><option value="NAKİT">NAKİT</option><option value="KREDİ KARTI">KREDİ KARTI</option></select></div><div class="field v436RoadCard" style="display:none"><label>HANGİ KART?</label><select name="roadCardId"><option value="">KART SEÇ</option>${(state.cards||[]).map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div></div>`;
 window.v436RoadToggle=function(f){const box=f.querySelector('.v436RoadExtra');if(box)box.style.display=(f.road?.value==='yes')?'block':'none'};
 window.v436RoadMethod=function(f){const box=f.querySelector('.v436RoadCard');if(box)box.style.display=(f.roadMethod?.value==='KREDİ KARTI')?'block':'none'};
 window.dailyForm=function(){return `<form class="v436WorkForm" onsubmit="submitDaily(event)">${field('date','TARİH',lastDate(),'date')}${field('title','İŞ / PROJE',remembered('lastDailyTitle','ANA İŞ'))}${field('amount','GÜNLÜK ÜCRET',remembered('lastDailyRate',state.settings.dailyRate),'number')}${payField('unpaid')}${roadFields()}${textarea('note','NOT')}<button class="primary">GÜNLÜK KAYDI EKLE</button></form>`};
 window.hourlyForm=function(){return `<form class="v436WorkForm" onsubmit="submitHourly(event)">${field('date','TARİH',lastDate(),'date')}${field('title','İŞ / PROJE',remembered('lastHourlyTitle','EK İŞ'))}${field('hours','ÇALIŞILAN SAAT',remembered('lastHourlyHours',0),'number')}${field('rate','SAATLİK ÜCRET',remembered('lastHourlyRate',state.settings.hourlyRate),'number')}${payField('unpaid')}${roadFields()}${textarea('note','NOT')}<button class="primary">SAATLİK KAYDI EKLE</button></form>`};
 window.overtimeForm=function(){return `<form class="v436WorkForm" onsubmit="submitOvertime(event)">${field('date','TARİH',lastDate(),'date')}${field('title','İŞ / PROJE',remembered('lastOvertimeTitle','ANA İŞ'))}${field('hours','MESAİ SÜRESİ',remembered('lastOvertimeHours',0),'number')}${field('rate','MESAİ SAATLİK ÜCRET',remembered('lastOvertimeRate',state.settings.overtimeRate),'number')}${payField('unpaid')}${textarea('note','NOT')}<button class="primary">MESAİ KAYDI EKLE</button></form>`};
 function remember(d,type){state.settings.lastWorkDate=d.date||lastDate();if(type==='daily'){state.settings.lastDailyTitle=d.title||'ANA İŞ';state.settings.lastDailyRate=+d.amount||0}else if(type==='hourly'){state.settings.lastHourlyTitle=d.title||'EK İŞ';state.settings.lastHourlyHours=+d.hours||0;state.settings.lastHourlyRate=+d.rate||0}else{state.settings.lastOvertimeTitle=d.title||'ANA İŞ';state.settings.lastOvertimeHours=+d.hours||0;state.settings.lastOvertimeRate=+d.rate||0}if(d.roadAmount!==undefined)state.settings.lastRoadAmount=+d.roadAmount||0;}
 function addRoad(d,workId){if(d.road!=='yes'||!(+d.roadAmount>0))return true;const method=d.roadMethod||'NAKİT';let card=null;if(method==='KREDİ KARTI'){card=(state.cards||[]).find(c=>c.id===d.roadCardId);if(!card){alert('Yol gideri için kredi kartı seçmelisiniz.');return false;}}
  const exp={id:uid(),date:d.date,title:'YOL',amount:+d.roadAmount,category:'YOL',method,cardId:card?.id||'',cardName:card?.name||'',sourceType:'workRoad',workId,note:'ÇALIŞMA YOL MASRAFI'};state.expenses.push(exp);
  if(card){card.balance=(+card.balance||0)+(+d.roadAmount||0);card.transactions=Array.isArray(card.transactions)?card.transactions:[];card.transactions.push({id:uid(),expenseId:exp.id,title:'YOL',amount:+d.roadAmount,date:d.date,type:'expense',category:'YOL'});}return true;}
 function addWork(type,d){const id=uid(),amount=type==='daily'?(+d.amount||0):(+d.hours||0)*(+d.rate||0);const w={id,type,date:d.date,title:upper(d.title||(type==='hourly'?'EK İŞ':'ANA İŞ')),amount,paymentStatus:d.paymentStatus||'unpaid',note:d.note||''};if(type!=='daily'){w.hours=+d.hours||0;w.rate=+d.rate||0;}state.work.push(w);if(type!=='overtime'&&!addRoad(d,id)){state.work=state.work.filter(x=>x.id!==id);return false;}return true;}
 window.submitDaily=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());remember(d,'daily');if(!addWork('daily',d))return;save();closeModal();render()};
 window.submitHourly=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());remember(d,'hourly');if(!addWork('hourly',d))return;save();closeModal();render()};
 window.submitOvertime=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());remember(d,'overtime');if(!addWork('overtime',d))return;save();closeModal();render()};
})();

;

/* ===== v437_work_roads.js ===== */
/* RUTIN V43.7 — work income is earned immediately; multiple road expenses per work record */
(function(){
 const E=s=>window.esc?window.esc(String(s??'')):String(s??'');
 const lastDate=()=>state.settings.lastWorkDate||iso();
 const remembered=(k,f)=>state.settings[k]!==undefined&&state.settings[k]!==''?state.settings[k]:f;
 const cards=()=>Array.isArray(state.cards)?state.cards:[];
 const methodOptions=(method='NAKİT',cardId='')=>`<select class="v437RoadMethod" onchange="v437ToggleCard(this)"><option value="NAKİT" ${method==='NAKİT'?'selected':''}>NAKİT</option><option value="KREDİ KARTI" ${String(method).includes('KREDİ')?'selected':''}>KREDİ KARTI</option></select><select class="v437RoadCard" ${String(method).includes('KREDİ')?'':'style="display:none"'}>${cards().map(c=>`<option value="${E(c.id)}" ${String(c.id)===String(cardId)?'selected':''}>${E(c.name||'KREDİ KARTI')}</option>`).join('')}</select>`;
 window.v437ToggleCard=function(sel){const card=sel.parentElement.querySelector('.v437RoadCard');if(card)card.style.display=sel.value==='KREDİ KARTI'?'':'none'};
 window.v437AddRoad=function(btn,road={}){const box=btn.closest('.v437RoadBox').querySelector('.v437RoadList');const row=document.createElement('div');row.className='v437RoadRow';row.innerHTML=`<select class="v437RoadDirection"><option value="GİDİŞ" ${road.direction==='GİDİŞ'?'selected':''}>GİDİŞ</option><option value="DÖNÜŞ" ${road.direction==='DÖNÜŞ'?'selected':''}>DÖNÜŞ</option><option value="YOL" ${!road.direction||road.direction==='YOL'?'selected':''}>YOL</option></select><input class="v437RoadAmount" type="number" inputmode="decimal" min="0" step="0.01" placeholder="TUTAR" value="${E(road.amount??state.settings.lastRoadAmount??'')}"><div class="v437RoadPay">${methodOptions(road.method||state.settings.lastRoadMethod||'NAKİT',road.cardId||state.settings.lastRoadCardId||'')}</div><button type="button" class="v437RoadRemove" onclick="this.closest('.v437RoadRow').remove()">×</button>`;box.appendChild(row)};
 function roadBox(existing=[]){return `<div class="v437RoadBox"><div class="v437RoadHead"><div><b>YOL GİDERLERİ</b><small>HER ARAÇ İÇİN AYRI ÖDEME EKLEYEBİLİRSİN</small></div></div><div class="v437RoadList"></div><button type="button" class="v437AddRoad" onclick="v437AddRoad(this)">＋ YOL EKLE</button><script type="application/json" class="v437Seed">${E(JSON.stringify(existing))}</script></div>`}
 function seedRoads(){document.querySelectorAll('.v437RoadBox').forEach(box=>{if(box.dataset.seeded)return;box.dataset.seeded='1';let a=[];try{a=JSON.parse(box.querySelector('.v437Seed')?.textContent||'[]')}catch(e){};const b=box.querySelector('.v437AddRoad');a.forEach(r=>v437AddRoad(b,r))})}
 const oldRender=window.render; window.render=function(){oldRender();setTimeout(seedRoads,0)};
 const oldOpen=window.openModal; window.openModal=function(k){oldOpen(k);setTimeout(seedRoads,0)};
 function form(type,x=null){const daily=type==='daily',hourly=type==='hourly',ot=type==='overtime';const roads=x?(state.expenses||[]).filter(r=>String(r.workId||'')===String(x.id)&&r.category==='YOL'):[];const date=x?.date||lastDate(), title=x?.title||remembered(daily?'lastDailyTitle':hourly?'lastHourlyTitle':'lastOvertimeTitle',daily||ot?'ANA İŞ':'EK İŞ');let fields=field('date','TARİH',date,'date')+field('title','İŞ / PROJE',title);if(daily)fields+=field('amount','GÜNLÜK ÜCRET',x?.amount??remembered('lastDailyRate',state.settings.dailyRate),'number');else fields+=field('hours',ot?'MESAİ SÜRESİ':'ÇALIŞILAN SAAT',x?.hours??remembered(ot?'lastOvertimeHours':'lastHourlyHours',0),'number')+field('rate',ot?'MESAİ SAATLİK ÜCRET':'SAATLİK ÜCRET',x?.rate??remembered(ot?'lastOvertimeRate':'lastHourlyRate',ot?state.settings.overtimeRate:state.settings.hourlyRate),'number');if(!ot)fields+=roadBox(roads);fields+=textarea('note','NOT',x?.note||'');return fields}
 window.dailyForm=()=>`<form class="v436WorkForm" onsubmit="v437SubmitWork(event,'daily')">${form('daily')}<button class="primary">GÜNLÜK KAYDI EKLE</button></form>`;
 window.hourlyForm=()=>`<form class="v436WorkForm" onsubmit="v437SubmitWork(event,'hourly')">${form('hourly')}<button class="primary">SAATLİK KAYDI EKLE</button></form>`;
 window.overtimeForm=()=>`<form class="v436WorkForm" onsubmit="v437SubmitWork(event,'overtime')">${form('overtime')}<button class="primary">MESAİ KAYDI EKLE</button></form>`;
 function remember(d,type){state.settings.lastWorkDate=d.date||lastDate();if(type==='daily'){state.settings.lastDailyTitle=d.title||'ANA İŞ';state.settings.lastDailyRate=+d.amount||0}else if(type==='hourly'){state.settings.lastHourlyTitle=d.title||'EK İŞ';state.settings.lastHourlyHours=+d.hours||0;state.settings.lastHourlyRate=+d.rate||0}else{state.settings.lastOvertimeTitle=d.title||'ANA İŞ';state.settings.lastOvertimeHours=+d.hours||0;state.settings.lastOvertimeRate=+d.rate||0}}
 function collectRoads(form,workId,date){return [...form.querySelectorAll('.v437RoadRow')].map(r=>{const amount=+r.querySelector('.v437RoadAmount').value||0, method=r.querySelector('.v437RoadMethod').value, direction=r.querySelector('.v437RoadDirection')?.value||'YOL', cardSel=r.querySelector('.v437RoadCard'), cardId=method==='KREDİ KARTI'?(cardSel?.value||''):'';const card=cards().find(c=>String(c.id)===String(cardId));if(amount>0){state.settings.lastRoadAmount=amount;state.settings.lastRoadMethod=method;state.settings.lastRoadCardId=cardId}return amount>0?{id:uid(),workId,date,title:'YOL',direction,amount,category:'YOL',method:method==='KREDİ KARTI'?'KREDİ KARTI':'NAKİT',cardId,cardName:card?.name||'',note:'ÇALIŞMA YOL GİDERİ'}:null}).filter(Boolean)}
 window.v437SubmitWork=function(e,type,id=''){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries());let x=id?state.work.find(z=>String(z.id)===String(id)):null;if(!x){x={id:uid(),type};state.work.push(x)}x.type=type;x.date=d.date;x.title=upper(d.title||'ÇALIŞMA');x.note=d.note||'';delete x.paymentStatus;if(type==='daily')x.amount=+d.amount||0;else{x.hours=+d.hours||0;x.rate=+d.rate||0;x.amount=x.hours*x.rate}remember(d,type);state.expenses=(state.expenses||[]).filter(r=>String(r.workId||'')!==String(x.id));if(type!=='overtime')state.expenses.push(...collectRoads(f,x.id,x.date));save();modal=null;render()};
 window.workRows=function(type){const a=state.work.filter(x=>x.type===type).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);return a.length?a.map(x=>{const rc=(state.expenses||[]).filter(r=>String(r.workId||'')===String(x.id)&&r.category==='YOL'),rt=rc.reduce((n,r)=>n+(+r.amount||0),0);return `<button class="v436WorkRow" onclick="openRecordV435('work','${E(x.id)}')"><div class="ico">${type==='daily'?'✓':type==='hourly'?'◷':'★'}</div><div class="v436WorkText"><b>${E(x.title)}</b><small>${E(x.date)}${x.hours?' · '+E(x.hours)+' SAAT':''}${rt?' · YOL '+money(rt):''}</small><em class="paid">KAZANÇ HESABA DAHİL</em></div><strong>${money(x.amount||0)}</strong><span>›</span></button>`}).join(''):'<div class="notice">HENÜZ KAYIT YOK.</div>'};
 const prevModal=window.modalHtml; window.modalHtml=function(k){if(k.startsWith('editRecord:work:')){const id=k.split(':')[2],x=state.work.find(z=>String(z.id)===String(id));if(!x)return prevModal(k);const label=x.type==='daily'?'GÜNLÜK ÇALIŞMA':x.type==='hourly'?'SAATLİK ÇALIŞMA':'MESAİ';return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${label}</b><button class="close" onclick="closeModal()">×</button></div><form class="v436WorkForm" onsubmit="v437SubmitWork(event,'${x.type}','${E(id)}')">${form(x.type,x)}<button class="primary">DEĞİŞİKLİĞİ KAYDET</button><button type="button" class="v4341Delete" onclick="v4341Delete('work','${E(id)}')">KAYDI SİL</button></form></div></div>`}return prevModal(k)};
 state.work.forEach(x=>{if(x.paymentStatus)delete x.paymentStatus}); save();
})();

;

/* ===== v438_road_grouping.js ===== */
/* RUTIN V43.8 — grouped daily road movement + individual road edit/delete */
(function(){
 const E=s=>window.esc?window.esc(String(s??'')):String(s??'');
 const roads=()=> (state.expenses||[]).filter(x=>String(x.category||'').toUpperCase()==='YOL' && x.workId);
 const sum=a=>a.reduce((n,x)=>n+(+x.amount||0),0);
 const groupKey=x=>`${x.date||''}__${x.workId||''}`;
 const groupFor=(date,workId)=>roads().filter(x=>String(x.date||'')===String(date||'')&&String(x.workId||'')===String(workId||''));
 const payTotals=a=>({cash:sum(a.filter(x=>String(x.method||'').toUpperCase().includes('NAKİT'))),card:sum(a.filter(x=>String(x.method||'').toUpperCase().includes('KREDİ')))});
 window.openRoadGroupV438=(date,workId)=>openModal(`roadGroupV438:${date}:${workId}`);
 window.deleteRoadV438=function(id,date,workId){if(!confirm('BU YOL ÖDEMESİ SİLİNSİN Mİ?'))return;state.expenses=(state.expenses||[]).filter(x=>String(x.id)!==String(id));save();openRoadGroupV438(date,workId);render()};
 function roadGroupCard(date,workId,a){const p=payTotals(a);return `<button class="roadGroupCardV438" onclick="openRoadGroupV438('${E(date)}','${E(workId)}')"><div class="roadGroupIconV438">🚗</div><div><b>YOL GİDERİ</b><small>${E(date)} · ${a.length} ÖDEME</small><em>${p.card?money(p.card)+' KART':''}${p.card&&p.cash?' · ':''}${p.cash?money(p.cash)+' NAKİT':''}</em></div><strong>-${money(sum(a))}</strong><span>›</span></button>`}
 function groupRoadItems(items){const normal=items.filter(x=>!(String(x.category||'').toUpperCase()==='YOL'&&x.workId));const gm={};items.filter(x=>String(x.category||'').toUpperCase()==='YOL'&&x.workId).forEach(x=>(gm[groupKey(x)]||(gm[groupKey(x)]=[])).push(x));return {normal,groups:Object.values(gm).sort((a,b)=>(b[0]?.date||'').localeCompare(a[0]?.date||''))}}
 window.roadGroupCardV438=roadGroupCard; window.groupRoadItemsV438=groupRoadItems;
 const prevModal=window.modalHtml; window.modalHtml=function(k){
   if(k.startsWith('roadGroupV438:')){const p=k.split(':'),date=p[1],workId=p.slice(2).join(':'),a=groupFor(date,workId),pt=payTotals(a);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet v438RoadSheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>YOL GİDERİ DETAYI</b><button class="close" onclick="closeModal()">×</button></div><div class="roadHeroV438"><small>${E(date)} · ${a.length} ÖDEME</small><strong>${money(sum(a))}</strong><div><span>💳 ${money(pt.card)} KART</span><span>💵 ${money(pt.cash)} NAKİT</span></div></div><div class="section"><b>YOL ÖDEMELERİ</b><span>TEK TEK DÜZENLE / SİL</span></div>${a.map((x,i)=>`<div class="roadItemV438"><button class="roadItemMainV438" onclick="openRecordV435('expense','${E(x.id)}')"><i>${E(x.direction||((i%2)?'DÖNÜŞ':'GİDİŞ'))}</i><div><b>${E(x.direction||'YOL')} · ${money(x.amount)}</b><small>${E(x.method||'NAKİT')}${x.cardName?' · '+E(x.cardName):''}</small></div><span>›</span></button><button class="roadItemDeleteV438" onclick="deleteRoadV438('${E(x.id)}','${E(date)}','${E(workId)}')">SİL</button></div>`).join('')||'<div class="notice">YOL ÖDEMESİ YOK.</div>'}</div></div>`}
   return prevModal(k)
 };
 // Reports: replace only the appended detailed movement area with grouped road display.
 const oldReports=window.reports; window.reports=function(){let h=oldReports();try{const marker='<div class="section"><b>AYRINTILI HAREKETLER</b>';const at=h.lastIndexOf(marker);if(at>=0){const base=h.slice(0,at);const s=state.reportStart||monthStart(),e=state.reportEnd||monthEnd();const inP=d=>d>=s&&d<=e;const work=(state.work||[]).filter(x=>inP(x.date)).sort((a,b)=>b.date.localeCompare(a.date));const inc=(state.incomes||[]).filter(x=>inP(x.date)).sort((a,b)=>b.date.localeCompare(a.date));const exp=(state.expenses||[]).filter(x=>inP(x.date));const g=groupRoadItems(exp), normal=g.normal.sort((a,b)=>(b.date||'').localeCompare(a.date||''));const wr=work.map(x=>`<button class="globalRecordRowV435" onclick="openRecordV435('work','${E(x.id)}')"><i>▣</i><div><b>${E(x.title||'ÇALIŞMA')}</b><small>${E(x.date)} · AYRINTI / DÜZENLE / SİL</small></div><strong class="gold">+${money(x.amount||0)}</strong><span>›</span></button>`).join('');const ir=inc.map(x=>`<button class="globalRecordRowV435" onclick="openRecordV435('income','${E(x.id)}')"><i>₺</i><div><b>${E(x.title||'DİĞER GELİR')}</b><small>${E(x.date)} · AYRINTI / DÜZENLE / SİL</small></div><strong class="green">+${money(x.amount||0)}</strong><span>›</span></button>`).join('');const er=normal.map(x=>`<button class="globalRecordRowV435" onclick="openRecordV435('expense','${E(x.id)}')"><i>${window.rutinCategoryIcon?window.rutinCategoryIcon(x.category||'DİĞER'):'₺'}</i><div><b>${E(x.category||x.title||'HARCAMA')}</b><small>${E(x.date)} · ${E(x.method||'NAKİT')} · AYRINTI / DÜZENLE / SİL</small></div><strong class="red">-${money(x.amount||0)}</strong><span>›</span></button>`).join('');const rg=g.groups.map(a=>roadGroupCard(a[0].date,a[0].workId,a)).join('');return base+`<div class="section"><b>AYRINTILI HAREKETLER</b><span>GRUPLU YOL</span></div><div class="reportGroupV435"><div class="section"><b>GELİR / ÇALIŞMA HAREKETLERİ</b><span>DOKUN → AYRINTI</span></div>${wr+ir||'<div class="notice">KAYIT YOK.</div>'}</div><div class="reportGroupV435"><div class="section"><b>HARCAMA / YOL HAREKETLERİ</b><span>YOL GÜN BAZINDA TEK KART</span></div>${rg+er||'<div class="notice">KAYIT YOK.</div>'}</div>`;}
   }catch(e){}return h};
 // Calendar day menu: collapse road rows into one daily card, while preserving other records.
 const oldCalendarScreen=window.calendarScreen; if(oldCalendarScreen){ /* display layer is handled by CSS/modal grouping where possible */ }
})();

;
